-- Finance Insights — reporting demo schema
-- Run on PostgreSQL 14+ (uses GENERATED BY DEFAULT AS IDENTITY).

BEGIN;

DROP TABLE IF EXISTS transaction_extra CASCADE;
DROP TABLE IF EXISTS merchant_secondary_tags CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    username text NOT NULL UNIQUE,
    password text NOT NULL
);

CREATE TABLE accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    bank_name text NOT NULL,
    account_number text NOT NULL,
    currency char(3) NOT NULL DEFAULT 'EUR'
);

CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('primary', 'secondary')),
    UNIQUE (name, type)
);

CREATE TABLE merchants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier_name text NOT NULL UNIQUE,
    primary_tag_id bigint NOT NULL REFERENCES tags (id),
    default_title text
);

CREATE TABLE merchant_secondary_tags (
    merchant_id bigint NOT NULL REFERENCES merchants (id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (merchant_id, tag_id)
);

CREATE TABLE transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    date date NOT NULL,
    bank_reference_number text,
    justification text,
    indicator text,
    merchant_identifier text,
    amount1 numeric(14, 2),
    mcc_code text,
    card_masked text,
    reference text,
    description text,
    payment_method text,
    direction text NOT NULL CHECK (direction IN ('debit', 'credit')),
    amount numeric(14, 2) NOT NULL,
    balance_after_transaction numeric(14, 2),
    statement_file_name text
);

CREATE TABLE transaction_extra (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id bigint NOT NULL UNIQUE REFERENCES transactions (id) ON DELETE CASCADE,
    note text,
    in_report boolean NOT NULL DEFAULT true,
    parser_name_version text
);

CREATE INDEX idx_transactions_account_date ON transactions (account_id, date);
CREATE INDEX idx_transactions_merchant ON transactions (merchant_identifier);
CREATE INDEX idx_transactions_direction_date ON transactions (direction, date);

COMMIT;
