-- Simplify the transactions table to match the new parser output.
-- Drops the old rich-schema table and recreates it with balance/amount as
-- plain integers and raw_data as a text array.

BEGIN;

DROP TABLE IF EXISTS transaction_extra CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;

CREATE TABLE transactions (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id            bigint NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    date                  date NOT NULL,
    bank_reference        text,
    transaction_reference text,
    merchant_identifier   text,
    balance_before        integer NOT NULL DEFAULT 0,
    balance_after         integer NOT NULL DEFAULT 0,
    amount                integer NOT NULL,
    direction             text NOT NULL CHECK (direction IN ('debit', 'credit')),
    raw_data              text[],
    statement_file_name   text
);

CREATE TABLE transaction_extra (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id bigint NOT NULL UNIQUE REFERENCES transactions (id) ON DELETE CASCADE,
    note           text,
    in_report      boolean NOT NULL DEFAULT true,
    parser_name_version text
);

CREATE INDEX idx_transactions_account_date ON transactions (account_id, date);
CREATE INDEX idx_transactions_merchant     ON transactions (merchant_identifier);
CREATE INDEX idx_transactions_direction_date ON transactions (direction, date);

COMMIT;
